//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlRichMenuMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zd1O6SNqTN8duuo14Zu/zGzJ6LZkpB8aENmUhc45T1b3wQHqESRPJI81Y3MKWO1xD9OclfSRx5gYgRhMm" +
            "vmcG/ytzsnOb4SanJL4jLxJtZvXxKpvs6G7nAQywXkJl6XT8ytN5xWqyGDUWvsph0nxIQdB04t89/1O/" +
            "w1cDnyilFU=\r\n")]
        public string ChannelAccessToken {
            get {
                return ((string)(this["ChannelAccessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U28aa279ed62b3e495b0f9d88f5a4afc2")]
        public string UserId {
            get {
                return ((string)(this["UserId"]));
            }
        }
    }
}
